name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "0 0 * * *" # every day at 12 AM
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python generate-json.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add movies.json series.json
          git commit -m "Update JSON from Google Sheets" || echo "No changes"
          git push
